### PR TITLE
Fix and finalise SVM and neural network model integration

### PR DESCRIPTION
**Pull request by wjohn564**

### CODE REVIEW

**Review by CaoimhinHawk1 — DISMISSED** [review]

**Review by AdamTCollins — APPROVED** [review]
Looks good and everything working fine, thanks. 🔥

**Review by oOoOoOo0o — APPROVED** [review]
Solid

**Review by M-Byte480 — APPROVED** [review]
Merge when possible

**Review by MartyD1 — APPROVED** [review]

**Comment by BrenyQT** [comment]
good merge

**Pull request merged**
