### PR TITLE
fixing minor bugs

### PR DESCRIPTION
**Pull request by M-Byte480**

### CODE REVIEW

**Review by oOoOoOo0o — APPROVED** [review]
Wow, nice catch man LGTM

**Review by italotrt — APPROVED** [review]
lgtm

**Review by tadhgryan2012 — APPROVED** [review]
lgtm

**Comment by Bojo992** [comment]
lgtm

omg-cant-believe

**Review by BrenyQT — APPROVED** [review]
SEND IT

**Pull request closed without merging**
